apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ebook-tools.fullname" . }}-backend
  labels:
    {{- include "ebook-tools.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
