apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ebook-tools.fullname" . }}-secrets
  labels:
    {{- include "ebook-tools.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | b64enc | quote }}
