apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ebook-tools.fullname" . }}-postgres-data
  labels:
    {{- include "ebook-tools.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.data.size }}
  {{- if .Values.postgres.persistence.data.hostPath }}
  storageClassName: ""
  volumeName: {{ include "ebook-tools.fullname" . }}-postgres-data
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ebook-tools.fullname" . }}-postgres-backups
  labels:
    {{- include "ebook-tools.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.backups.size }}
  {{- if .Values.postgres.persistence.backups.hostPath }}
  storageClassName: ""
  volumeName: {{ include "ebook-tools.fullname" . }}-postgres-backups
  {{- end }}
